name: Build

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "release/**"
      - "hotfix/**"
    tags:
      - "*"
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2022, ubuntu-22.04, macos-12 ]
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
      AZURE_USER: ${{ secrets.AZURE_USER }}
      AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
      AZURE_SOURCE: ${{ secrets.AZURE_SOURCE }}
      GPR_USER: ${{ secrets.GPR_USER }}
      GPR_PASSWORD: ${{ secrets.GPR_PASSWORD }}
      GPR_SOURCE: ${{ secrets.GPR_SOURCE }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      NUGET_SOURCE: "https://api.nuget.org/v3/index.json"
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      #WYAM_ACCESS_TOKEN: ${{ secrets.WYAM_ACCESS_TOKEN }}
      #WYAM_DEPLOY_BRANCH: "gh-pages"
      #WYAM_DEPLOY_REMOTE: ${{ github.event.repository.html_url }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
        with:
          # codecov needs 2.1
          dotnet-version: |
            2.1
            3.1
            5.0
            6.0
            7.0
      - name: Cache Tools
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}
      - name: Build project
        uses: cake-build/cake-action@a6eb054329257c9e70a6c6bf01747ad6e1d9d52b # v1
        with:
          script-path: recipe.cake
          target: CI
          cake-version: 1.3.0
      - name: Upload Issues
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          if-no-files-found: warn
          name: ${{ matrix.os }} Issues
          path: |
            BuildArtifacts/report.html
            BuildArtifacts/**/coverlet/*.xml
      - name: Upload Packages
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        if: runner.os == 'Windows'
        with:
          if-no-files-found: warn
          name: package
          path: BuildArtifacts/Packages/**/*
